### ISSUE TITLE
Implement socket basics

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-fixture-socket#2]
- [x] can get a message and send one back
- [x] can simulate a basic RESTful-ish socket connection using `can.fixture.store`.

**Comment by ilyavf** [comment]
See [basic test](https://github.com/canjs/can-fixture-socket/blob/master/test/test.js#L21) and [CRUD test](https://github.com/canjs/can-fixture-socket/blob/master/test/test.js#L50).

Implementation: [src/index.js](https://github.com/canjs/can-fixture-socket/blob/master/src/index.js)
