### ISSUE TITLE
Silence the console noise

### ISSUE THREAD

**Issue by BigAB** [canjs/can-fixture-socket#5]
We need an option to turn off the noise in the console:

![image](https://cloud.githubusercontent.com/assets/76821/20358463/7fd9684a-abf1-11e6-90b6-d9637d691b21.png)

Some sort of configuration or something

**Comment by ilyavf** [comment]
Fixed in `0.5.9` with 685eae7a5bed8c0fc5f8889c3f360c6b118348d6
